go.property("speed", 250)
function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") or not action_id then
		local current_pos = go.get_position()
		local target_pos = vmath.vector3(action.x, action.y, 0)
		local distance = vmath.length(target_pos - current_pos)
		local duration = distance / self.speed
		go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, target_pos, go.EASING_LINEAR, duration, 0)
	end
end
